// Generated by Wrangler on Wed Sep 04 2024 11:25:36 GMT-0700 (Mountain Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`
// Extended with PayPal and other environment variables

interface CloudflareEnv {
	DATABASE: D1Database;

	// Durable Objects
	CONVERSATION_WS: DurableObjectNamespace;

	// PayPal Configuration
	PAYPAL_CLIENT_ID?: string;
	PAYPAL_CLIENT_SECRET?: string;
	PAYPAL_API_BASE?: string;
	PAYPAL_WEBHOOK_ID?: string;
	PAYPAL_SUBSCRIPTION_PLAN_ID?: string;

	// Stripe Configuration
	STRIPE_SECRET_KEY?: string;
	STRIPE_WEBHOOK_SECRET?: string;

	// Auth Configuration
	AUTH_SECRET?: string;
	AUTH_GOOGLE_ID?: string;
	AUTH_GOOGLE_SECRET?: string;

	// Other
	SUPER_USER_EMAIL?: string;
}
