-- Migration: Change support_tickets.id from INTEGER to TEXT (6-character alphanumeric)
-- SQLite doesn't support ALTER COLUMN, so we recreate the table

-- Step 1: Drop existing trigger
DROP TRIGGER IF EXISTS update_support_tickets_updated_at;

-- Step 2: Create new table with TEXT id
CREATE TABLE support_tickets_new (
  id TEXT PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  company_id INTEGER REFERENCES companies(id) ON DELETE SET NULL,
  subject TEXT NOT NULL,
  description TEXT NOT NULL,
  urgency TEXT NOT NULL CHECK(urgency IN ('minor', 'urgent', 'critical')),
  status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open', 'in_progress', 'resolved', 'closed')),
  assigned_to_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  internal_notes TEXT,
  admin_response TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch()),
  resolved_at INTEGER
);

-- Step 3: Copy existing data with generated IDs
-- Using hex(randomblob(3)) generates a 6-character hex string as temporary ID
-- In production, proper IDs will be generated by the application
INSERT INTO support_tickets_new (id, user_id, company_id, subject, description, urgency, status, assigned_to_user_id, internal_notes, admin_response, created_at, updated_at, resolved_at)
SELECT
  upper(substr(hex(randomblob(3)), 1, 6)) as id,
  user_id, company_id, subject, description, urgency, status, assigned_to_user_id, internal_notes, admin_response, created_at, updated_at, resolved_at
FROM support_tickets;

-- Step 4: Drop old table
DROP TABLE support_tickets;

-- Step 5: Rename new table
ALTER TABLE support_tickets_new RENAME TO support_tickets;

-- Step 6: Recreate indexes
CREATE INDEX idx_support_tickets_user ON support_tickets(user_id);
CREATE INDEX idx_support_tickets_status ON support_tickets(status);
CREATE INDEX idx_support_tickets_urgency ON support_tickets(urgency);
CREATE INDEX idx_support_tickets_status_urgency ON support_tickets(status, urgency);
CREATE INDEX idx_support_tickets_company ON support_tickets(company_id);
CREATE INDEX idx_support_tickets_assigned ON support_tickets(assigned_to_user_id);

-- Step 7: Recreate the updated_at trigger
CREATE TRIGGER update_support_tickets_updated_at
AFTER UPDATE ON support_tickets
FOR EACH ROW
BEGIN
  UPDATE support_tickets SET updated_at = unixepoch() WHERE id = NEW.id;
END;
